# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1f68940b3e520e4682ff97f6d172083e5ce0d648b561d59e69aa84812153a8f62592ed53d0fdffee64b6f278625cedd63b319885aa0f7f001889b5c4d005232

test:
  secret_key_base: 31fda0c9459a339060cc1ef2f02e26f6128d40c599c858fb16228e1e42fd7783b7f485006b84a32467c6b3fc60a4508dff8d5b2b48cf690a6781aa32a1f430de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
